# GlacierCam settings file: 
# See: https://github.com/Eagleshot/GlacierCam/blob/main/settings.yaml
cameraName: "Camera1"

# Camera resolution
# Select [0, 0] for maximum resolution
# Has to be between 64x64 and 4608x2592
resolution: [0, 0]

# Camera schedule (UTC time)
startTimeHour: 8
startTimeMinute: 0
endTimeHour: 18
endTimeMinute: 0
enableSunriseSunset: false # Overwrite start/end time with sunrise/sunset
intervalHours: 0 # Interval between photos
intervalMinutes: 30
timeSync: false # Automatic time synchronization with internet

# Location settings
enableGPS: false # Enable/disable GPS module
locationOverwrite: false # Manually ovewrite location (set location below)
latitude: 0.0
longitude: 0.0

# Diagnostics data
logLevel: "WARNING" # 'DEBUG', 'INFO', 'WARNING', 'ERROR' or 'CRITICAL'
uploadExtendedDiagnostics: false

# Battery settings
overwriteVoltageThresholds: false # Manually overwrite voltage thresholds
lowVoltageThreshold: 0.0 # Camera will shutdown if voltage drops below this value
recoveryVoltageThreshold: 0.0 # Camera will restart if voltage rises above this value
batteryVoltageHalf: 12.0 # Battery voltage at 50% capacity

# DANGER ZONE
shutdown: true # Enable or disable shutdown after program has run